### ISSUE TITLE
Step 2: My Profile

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#16]
1) Design Implementation
2) Back end part: all data to tables

**Comment by EmileKrm** [comment]
*** User Story ***

As a **User** I want to  ** complete the form** so that **I can move forward with my application**

*** Acceptance criteria ***
- [ ] User must be able to see first name, last name, date of birth pre-filled if he connected one of his social media
- [ ] User must be able to fill in all additional information
- [ ] User must be able to save and go to next step
- [ ] User must be able to see that he is at the second step of the unboarding

*** Definition of done ***

- [ ] Verify correct storage of information
- [ ] Verify that user can resume on-boarding if he disconnects from the website
- [ ] Validate designs

**Comment by EmileKrm** [comment]
Here are the designs:
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5992a1f78d540680ef8e6cb4

**Comment by EmileKrm** [comment]
@buzjuka 
[link for the specs](https://docs.google.com/spreadsheets/d/1ljgr7-uQRoGqiFj-_lrfdFfgH3G1ymwioFY5UyNVni0/edit#gid=979711233)
![image](https://user-images.githubusercontent.com/25280550/29453978-d81d9ad8-840b-11e7-85af-5ea6cd484c96.png)

**Comment by MariaUvarova** [comment]
Looks good http://joxi.ru/V2V69ooC081BY2 http://joxi.ru/krDgBoou0g1GWA http://joxi.ru/DrlKX33T4GMKEA http://joxi.ru/vAWW9oohkBY3xA

**Comment by MariaUvarova** [comment]
1) go to https://garant-me.herokuapp.com,
2) do the step 1 and click "Save & Next" http://joxi.ru/LmGgBoouRBwj3m,
3) fill all the fields http://joxi.ru/Grql7kkCNz4jQA http://joxi.ru/52aX6DDHGlER7m
4) try to test this page on Chrome in order to see how it looks on different devices http://joxi.ru/L215EOOF6wR1N2 http://joxi.ru/p27ZByyT0LKqkm
5) click "Save & Next" or "Previous" http://joxi.ru/D2Pg9ooudwqbPm Both buttons work fine.
6) Result: the page works well

**Comment by EmileKrm** [comment]
1 - International phone input [not implemented](http://joxi.net/ZrJJ7B1C1by1Zr) did you use the specs?[ link](https://intl-tel-input.com/)
2 - For cities it is not clear to the user that there is a dropdown menu [link](http://joxi.net/5md4X1xHvadkKm). There should ba an arrow, isn't it a default setting?
3 - wrong error message for date of birth [link](http://joxi.net/nAykWpZTXaRj7m)
4 - Future dates for date of birth should be blocked
5 - Past dates for move in date should be blocked 
6 - We feel that the date picker is not appropriate for date of birth. Can we switch to another display?

**Comment by EmileKrm** [comment]
7 - Display of text on mobile is not working
![image uploaded from ios 2](https://user-images.githubusercontent.com/25280550/29619685-f8addb8c-881b-11e7-8231-a67e12504f68.jpg)

**Comment by yuliyasychugova** [comment]
1 - International phone input not implemented did you use the specs? link - sorry, didn't notice that, will fix. 
2 - For cities it is not clear to the user that there is a dropdown menu link. There should ba an arrow, isn't it a default setting? - no, we used standard select2, we used it, Arrow is not a default setting, can you please send me an example?
3 - wrong error message for date of birth link - fixed
4 - Future dates for date of birth should be blocked - that wasn't stated in specs, we will do that, it won't take much time. 
5 - Past dates for move in date should be blocked - that wasn't stated in specs, we will do that, it won't take much time. 
6 - We feel that the date picker is not appropriate for date of birth. Can we switch to another display? - This is a date picked that you added in specs. What option would you like to see here?

**Comment by yuliyasychugova** [comment]
@EmileKrm 7 - Display of text on mobile is not working - what device did you use?

**Comment by EmileKrm** [comment]
iphone 6S google chrome

**Comment by yuliyasychugova** [comment]
Things fixed:  
 - Mobile layout
 - Arrow for cities

**Comment by EmileKrm** [comment]
2 - For cities it is not clear to the user that there is a dropdown menu link. There should ba an arrow, isn't it a default setting? - no, we used standard select2, we used it, Arrow is not a default setting, can you please send me an example? here is an example [link](http://joxi.net/8236DWJU6aYWlm)
4 - Future dates for date of birth should be blocked - that wasn't stated in specs, we will do that, it won't take much time. **EK:** Thank you, I remember doing it on the prototype it's one line of javascript
5 - Past dates for move in date should be blocked - that wasn't stated in specs, we will do that, it won't take much time. **EK:** Thank you, I remember doing it on the prototype it's one line of javascript
6 - We feel that the date picker is not appropriate for date of birth. Can we switch to another display? - This is a date picked that you added in specs. What option would you like to see here? EK: this is an [example](http://joxi.net/8236DWJU6aYelm) we can leave it for another sprint if it takes too much time.

**Comment by yuliyasychugova** [comment]
International phone input not implemented did you use the specs? link - sorry, didn't notice that, will fix. - fixed
