### ISSUE TITLE
Step 2 a: Professional Status

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#17]
Documents upload relating to a status of a client.

**Comment by EmileKrm** [comment]
*** User Story ***

As a **User** I want to **select my professional status** so that **my application gets completed in order to move to next step**

*** Acceptance criteria ***
- [ ] User must be able to select only one option
- [ ] User must be able to see different fields appear according to the selected option
- [ ] User must be able to select a school from a dropdown menu
- [ ] User must be able to fill in his budget

*** Definition of done ***

- [ ] Verify data validations and correct storage of information
- [ ] Validate designs

**Comment by EmileKrm** [comment]
Here are the designs:
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5992a663259ec74eed1857b1
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5992a7a0390fd950104b731a
Apply same design for the rest of the tabs
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5992a6860d0812faed04ebf9

**Comment by EmileKrm** [comment]
@buzjuka use university_default. svg for default university photo [link](https://drive.google.com/drive/u/1/folders/0B4cm2V76C2RcdXJzTTJPTndjaXM)

**Comment by EmileKrm** [comment]
@buzjuka, I found two JSON files for french school DB:
- [link](https://raw.githubusercontent.com/EmileKrm/garantmeapp/master/db/french_universities.json)
The school name is in the variable uo_lib(in french) and uo_lib_en(in english)
- [link](https://raw.githubusercontent.com/EmileKrm/garantmeapp/master/db/universities.json)
In this DB you have to 
          1 - Filter and take only schools with variable alpha_two_code = FR.
          2 - School name is in the variable name

**Comment by MariaUvarova** [comment]
It looks okay. http://joxi.ru/Grql7kkCNR1GWA http://joxi.ru/eAOE9ooc46ykPm http://joxi.ru/nAypGggtXaOw12 http://joxi.ru/YmEgBoouZBnB0A http://joxi.ru/E2p3yxxtB4d4am

**Comment by MariaUvarova** [comment]
1) go to https://garant-me.herokuapp.com,
2) do the step 1 and click "Save & Next" http://joxi.ru/LmGgBoouRBwj3m,
3) fill all the fields http://joxi.ru/Grql7kkCNz4jQA http://joxi.ru/52aX6DDHGlER7m
4) try to test this page on Chrome in order to see how it looks on different devices http://joxi.ru/Q2Kg9oou9OLkP2 http://joxi.ru/4AkLnRRUMjo4Vr,
5) click "Save & Next" or "Previous" http://joxi.ru/D2Pg9ooudwqbPm Both buttons work fine. 
6) Result: the page works well

**Comment by EmileKrm** [comment]
Professional status works well. Like agreed the adding a school manually feature will be done in another sprint
