### ISSUE TITLE
Step 3: My responsible party

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#18]
1) Design Implementation 
2) Back end part: All fields to tables

**Comment by EmileKrm** [comment]
*** User Story ***

As a **User** I want to **provide a responsible party** so that **my application gets completed in order to move to next step**

*** Acceptance criteria ***
- [ ] User must be able to select only one option Yes/No
- [ ] User must be able to see different fields appear according to the selected option
- [ ] User must be able to understand what is a responsible party
- [ ] User must be able to fill information relevant to responsible party

*** Definition of done ***

- [ ] Verify data validations and correct storage of information
- [ ] Validate designs

**Comment by EmileKrm** [comment]
Here are the designs:
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5995b0866cfef0d006b38cee
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5995b0866cfef0d006b38cee
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/5995b097cfdb769920aec738

NB: insert the explanatory pocess as an image, don't waste time coding it

**Comment by EmileKrm** [comment]
Text should have the same color [link](http://joxi.net/V2V4z6lH08OYbr) use #1b1b1b for all text

**Comment by MariaUvarova** [comment]
it works fine

**Comment by EmileKrm** [comment]
1 - I have this weird error message when I subit responsible party info
![image](https://user-images.githubusercontent.com/25280550/29675623-fc9abab4-88f5-11e7-8cbe-1a57edd6a066.png)
2 - Trouble with saving responsible party income. It only saves 10 no matter what number I put

**Comment by yuliyasychugova** [comment]
Fixed

**Comment by EmileKrm** [comment]
Looks good, thank you
