### ISSUE TITLE
Step 4: My documents

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#19]
1) Design Implementation 
2) Saving documents and transferring data to Admin panel

**Comment by EmileKrm** [comment]
*** User Story ***

As a **User** I want to **upload documents** so that **my application gets submitted**

*** Acceptance criteria ***
- [ ] User must be  able to upload documents in different formats: JPG, PDF
- [ ] User must be able to see that documents have been successfully uploaded
- [ ] User must be able to save his progress and move to dashboard

*** Definition of done ***

- [ ] Verify data validations and correct storage of information
- [ ] Verify that documents are being transferred to Admin Panel
- [ ] Verify size criteria for documents 
- [ ] Validate designs

**Comment by EmileKrm** [comment]
Here are the designs:

https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/599ad7fa7fa8a318992646d8

https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/599ad813c5fd36bd7c242f7d

**Comment by EmileKrm** [comment]
@k41n Are there any standards for upload size limit ? (documents and images)

**Comment by yuliyasychugova** [comment]
Layout: 
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/599ad813c5fd36bd7c242f7d

**Comment by yuliyasychugova** [comment]
@EmileKrm it would be great if we set 50mb per document as a restiction.

**Comment by EmileKrm** [comment]
@yuliyasychugova sounds good but why 50? is there a particular reason?

**Comment by yuliyasychugova** [comment]
PDF documents can be quite large, Andrei says it's better to set 50mb. As for standards, usually we set 5mb.24.08.2017, 16:17, "Emile Karam" <notifications@github.com>:@yuliyasychugova sounds good but why 50? is there a particular reason?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- Regards,Yuliya SychugovaProject ManagerKodep LLC

**Comment by EmileKrm** [comment]
Thank you for the clarification

**Comment by MariaUvarova** [comment]
1) the font here is bigger than it should be http://joxi.ru/bmoR1XXcMOXB0r
2) the button is called "submit" http://joxi.ru/xAeyKWWSYMPQKA
3) this text is missing http://joxi.ru/a2Xl9ooCyQaXn2
4) doesn't look good on mobile devices http://joxi.ru/a2Xl9ooCyQaXn2 http://joxi.ru/823WBXXh6z4Pa2 http://joxi.ru/zANM9ooIl1ZeO2 http://joxi.ru/Grql7kkCNzY3OA

**Comment by MariaUvarova** [comment]
works fine. ready to be checked

**Comment by EmileKrm** [comment]
@yuliyasychugova 

1 - When clicking on previous user goes back to my profile instead of my responsible party
2 - When user uploads documents and leaves page he doesn't see already uploaded documents. Did it save? Do documents get saved as soon as it is uploaded or do I have to click submit?

Great job for the logic responsible of adapting documents to professional status and the upload looks awesome!

**Comment by yuliyasychugova** [comment]
@EmileKrm 1) Will check it
2) Yes, it saves at the moment while loading. So when you click Submit, it's ready to be submitted.

**Comment by yuliyasychugova** [comment]
@EmileKrm 1) fixed, please check

**Comment by EmileKrm** [comment]
1) it doesn't work in this case: 
User submit step4 and then click on back to go back to step 4
User then clicks on previous. The web app takes him to my profile instead of my RP
