### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#27]
*** User Story ***

As a **Customer** I want **to know what are the steps of the on-boarding** so that **I can plan its completion**

As a **Customer** I want to **navigate between the completed steps** so that **I can edit my application**

*** Acceptance criteria ***

- [x] Customer must be able to see in which step he is
- [ ] Customer must be able to navigate between the completed tasks
- [ ]  Must be able to click on validated icons to go to the appropriate step
- [ ] Unvalidated steps must remain blocked

*** Definition of done ***

- [x] Trust bar look like designs in the mockups
- [ ] Successful test on localhost and heroku

**Comment by EmileKrm** [comment]
Here is the design:
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/598c7985a1f0c405e0cc92cc

**Comment by EmileKrm** [comment]
Intermediary bar shouldn't be active before going to next step [active bar](http://joxi.net/Q2Kl8gyU9y6NxA)
it should be [non active](http://joxi.net/8AndgaMTqo9YDm)

Same for all steps

**Comment by EmileKrm** [comment]
User should be able to click on validated steps to go back and check his responses (Only non-validated steps are bloacked)

**Comment by yuliyasychugova** [comment]
@EmileKrm about this: 
"Intermediary bar shouldn't be active before going to next step active bar
it should be non active"
Am I right that you mean that the user being on the third step shouldn't see the Step 3 active? Unfortunately, we used designs as a reference and here we have it active. 

About this: "User should be able to click on validated steps to go back and check his responses (Only non-validated steps are blocked)" - now this functionalities are done with the help of "previous" button. Should we add it to icons as well? Unfortunately, that wasn't stated clearly, that's why we didn't do that.

**Comment by EmileKrm** [comment]
1 - Step 3 should be active but the straight bar right after shouldn't. I'm talking about this 
![Uploading image.png…]()

**Comment by EmileKrm** [comment]
2 - It's okay we are going to need this feature anyway. If it takes too much time now we can do it on another sprint

**Comment by yuliyasychugova** [comment]
@EmileKrm 1 - Do you mean a line after My profile? https://gyazo.com/994183b78f51437e8864a19542061319 

2 - Let's say it this way - if you need this sprint to be done in time, we should leave it to the next sprint. If it's okay that we can be late, we can do it in the scope of this task.

**Comment by yuliyasychugova** [comment]
2 - We add this functionality to the next step, @buzjuka please skip it for now.
1 - Please change the logics about the lines after the step.

**Comment by MariaUvarova** [comment]
works fine
