### ISSUE TITLE
Forgot password layout

### ISSUE THREAD

**Issue by yuliyasychugova** [Garantme/Garantme_application#33]
https://app.zeplin.io/project/598b122ec551c21f559ad6ae/screen/59915a78afc70ede254716c1 

Here's the design

**Comment by EmileKrm** [comment]
@buzjuka the design looks good thank you

**Comment by MariaUvarova** [comment]
1. Go to https://garant-me.herokuapp.com/users/password/new (Incognito mode)
2. The design looks appropriate http://joxi.ru/Y2Ll9ooCnM77l2
3. Then press F12 in order to check the design in responsive http://joxi.ru/52aX6DDHGgEg9m
4. It's also possible to check it on different devices http://joxi.ru/12Mg9oou4wlwGr http://joxi.ru/v29RB88cGRZRJA
5. Result: the design looks appropriate

**Comment by yuliyasychugova** [comment]
@EmileKrm Please check it, if it's okay, we will merge it to master branch.

**Comment by EmileKrm** [comment]
@MariaUvarova @buzjuka thank you the design looks good on all type of devices. You van merge 👍 :)
