### ISSUE TITLE
Admin CRUD users

### ISSUE THREAD

**Issue by EmileKrm** [Garantme/Garantme_application#49]
*** User Story ***

As an Admin I want to CRUD users so that I can help them complete the on-boarding

*** Acceptance criteria ***

- [ ] Must be able to CRUD users

*** Definition of done ***

- [ ] Successfully complete all CRUD actions on a user

**Comment by EmileKrm** [comment]
@yuliyasychugova can we CRUD all models as Admin or is it safer to block some models?

**Comment by EmileKrm** [comment]
@yuliyasychugova in the prototype I developed with active admin I had the opportunity to edit everything by default. Do we really need to log in as user?
check the following:
[Edit of application](http://joxi.net/n2Yb6LWTj7JbxA)
[Edit of User](http://joxi.net/zANJqMNCl836OA)
[Edit of schools](http://joxi.net/EA4WDdqHDv4OV2)

I don't understand the need for login as user, why we can't do it with active admin only?

**Comment by buzjuka** [comment]
@EmileKrm 
We can easily make editing of tables in DB.
But if you want to fill in data step by step the way user does, we need to customize some methods of curren form objects, in order to user them in active admin or implement custom pages in admin panel (by implementing logics that we already used for a user).
IMO, the best option is to do standard pages for management in AA and make Admin a possibility to log in as a user and see/update the current state.
Anyway, if you need the same step by step filling data in AA, we can do it but it will take more time than Log in as a user option.

**Comment by EmileKrm** [comment]
No need to fill in info like user. Editing tables in DB is more than enough. This is what i need nothing more.

**Comment by EmileKrm** [comment]
**YY:**
Let's imagine the following situation 
- When you try to find the school you went in but you cannot find it, you have a possibility to type it
and go to the next step.

option 1: Should we add this school to a database without any approval after user typed it?
option 2: we should let them go to the next step but add a possibility to approve or disapprove the school by admins

**EK:**
- if we add it automatically, can Admin edit this information later on?
- How much extra time will you need for the approve/disapprove feature?

**YY:**
We can ask user to input it, add this name of school he entered into db,user goes to the next step and then admin will approve or disapprove this school, so other users would have a possibility to find this school as well.

- The only thing we need to work out if what happens if admin disapproves this school

**EK:**
If admin disapprove school, he can replace it with an existing school?

**YY:**
I think admin can edit it, yes

**Comment by EmileKrm** [comment]
We might not need this feature

**Comment by EmileKrm** [comment]
Not relevant
